### PR TITLE
Link ui model prototype

### PR DESCRIPTION
**Pull request by billlyzhaoyh**
There are still a few awkward implementations here:
- The cluster's workers are running in single-threaded mode since the compartmental model uses ode solver that does not allow multi-threading: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.html
 - The model results are saved to local disk first (as a result of model run finishes from model runner) and then they are collated together to save to disk (which can be replaced by a DB write). Need to temporarily gather results in memory rather than saving it to disk in the first place which will require changing the model runner object
- Currently, the batch runs are not leveraging model running now and model running history in the model runner class. It will probably be good to implement something similar so a batch job is not submitted again unless some of the model runs either fail or get cancelled.
- The model results seem to be off for arbitrary camp (investigating now)

### CODE REVIEW

**Comment by billlyzhaoyh** [comment]
Code changes for parameter loading in Compartmental model break ABM tests. Need to change the test now to read from local test files since the models wouldn't have the input parameters available until there is user input. Might be a good time to revise the testing suite for all three models.

**Comment by billlyzhaoyh** [comment]
The infection number is broken due to population vector change and that will be fixed soon.
Next step is to set the compartmental model profiles dynamically in a script so it scales with population number or else ode solver can mysteriously break due to some ill conditions imposed by the profile. For example, trying to remove residents at high risk at 30 people/day but then there are not many residents at high risk thus resulting in a negative number

**Review by pardf — APPROVED** [review]

**Comment by pardf** [comment]
@billlyzhaoyh could we do smaller PR in future as it would be easier to review and comment, etc.? Thanks

Waiting page needs to be updated but can be revised later

**Comment by billlyzhaoyh** [comment]
Noted that the session id is set to a fixed number for reading in the InputParameterCache but that will change once the data segregation is done.

**Review by kariso2000 — APPROVED** [review]

**Pull request merged**
