### PR TITLE
Contact matrices for countries and handler code in initialize_parameters.py

### PR DESCRIPTION
**Pull request by utkarshsahu**

### CODE REVIEW

**Review by titorenko — APPROVED** [review]

**Review by yanhong-zhao-ef — COMMENTED** [review]
I am thinking about how can do we better about inputting country parameters... maybe an Enum class? We probably want to throw a more intelligible error like 'Country not found' rather than the file is not found.

**Review by yanhong-zhao-ef — CHANGES_REQUESTED** [review]
Have you made changes in input_params CSV that take in a country-specific parameter?

**Comment by utkarshsahu** [comment]
> Have you made changes in input_params CSV that take in a country-specific parameter? Need to change the current reading from this file https://github.com/AIforGoodSimulator/model-server/blob/new_camp_experiments/fs/params/contact_matrix_params.csv logic

Not yet. I'll remove this contact matrix that we're currently using and replace it with country based logic. Just one thing to ask, from where in UI are we going to float these values around? Should I take country name as a parameter for our constructor to Parameters class or somewhere else?

**Comment by utkarshsahu** [comment]
> I am thinking about how can do we better about inputting country parameters... maybe an Enum class? We probably want to throw a more intelligible error like 'Country not found' rather than the file is not found.

We can have a config file in .ini format with the mappings from country to CSVs or a python file with a dictionary containing all the mappings. What approach seems suitable? Any one of these approaches would allow us to give better error messages.

**Comment by pardf** [comment]
> 
> 
> > Have you made changes in input_params CSV that take in a country-specific parameter? Need to change the current reading from this file https://github.com/AIforGoodSimulator/model-server/blob/new_camp_experiments/fs/params/contact_matrix_params.csv logic
> 
> Not yet. I'll remove this contact matrix that we're currently using and replace it with country based logic. Should I also rename all the contact matrix CSVs to a standard naming format? Currently, some of the CSVs are also named like this: Venezuela (Bolivarian Republic).csv .
> 
> Just one thing to ask, from where in UI are we going to float these values around? Should I take country name as a parameter for our constructor to Parameters class or somewhere else?

HI @utkarshsahu country names will here in 2 places (i) simplified UI (for non-technical end-user) and (ii) run_model (for data scientists) ... another UI - advanced UI does not need country input as it can capture from simplified UI if needed.

**Comment by pardf** [comment]
> 
> 
> > I am thinking about how can do we better about inputting country parameters... maybe an Enum class? We probably want to throw a more intelligible error like 'Country not found' rather than the file is not found.
> 
> We can have a config file in .ini format with the mappings from country to CSVs or a python file with a dictionary containing all the mappings. What approach seems suitable? Any one of these approaches would allow us to give better error messages.

Hi @billlyzhaoyh @yanhong-zhao-ef @utkarshsahu we can think about returning all files from the directory and based on the filenames - expose that as a list for users to choose from - this means the list is dynamic and always current, eliminating the need to update the list on a periodic basis or risk getting out of date.

**Comment by pardf** [comment]
> 
> 
> > > I am thinking about how can do we better about inputting country parameters... maybe an Enum class? We probably want to throw a more intelligible error like 'Country not found' rather than the file is not found.
> > 
> > 
> > We can have a config file in .ini format with the mappings from country to CSVs or a python file with a dictionary containing all the mappings. What approach seems suitable? Any one of these approaches would allow us to give better error messages.
> 
> Hi @billlyzhaoyh @yanhong-zhao-ef @utkarshsahu we can think about returning all files from the directory and based on the filenames - expose that as a list for users to choose from - this means the list is dynamic and always current, eliminating the need to update the list on a periodic basis or risk getting out of date.

Also could you provide the reference where all the contact matrices can be obtained? For example, a paper publication or website with those information would be sufficient. Thanks

**Review by pardf — APPROVED** [review]

**Review by billlyzhaoyh — COMMENTED** [review]
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005697 is where the POLYMOD contact matrices are obtained

**Review by billlyzhaoyh — COMMENTED** [review]
@utkarshsahu we are going to take the country as a parameter from the user and you just have to make sure the compartment model will take a parameter. I think the approach you proposed and what Peter said both make sense so if you can just implement one of them to your liking and submit a commit again, that will be great

**Review by kariso2000 — APPROVED** [review]

**Review by billlyzhaoyh — APPROVED** [review]
Great work Utkarsh!

**Comment by billlyzhaoyh** [comment]
@pardf please notice the country map implementation here - maybe the dropdown country-input can take that as well but if it takes too much time then I can wire them up later

**Comment by pardf** [comment]
> 
> 
> @pardf please notice the country map implementation here - maybe the dropdown country-input can take that as well but if it takes too much time then I can wire them up later

HI @billlyzhaoyh @utkarshsahu the dynamic country listing is completed in the simplified UI - strictly speaking there is no need for the code to contain a list of the countries and how they are mapped to the corresponding csv file

@utkarshsahu could you update the code such that - the csv file is whatever the values of the corresponding parameter added with '.csv' - e.g. 'Germany' -> 'Germany.csv'. This will make the country list truly dynamic. Thanks.

**Comment by utkarshsahu** [comment]
> @utkarshsahu could you update the code such that - the csv file is whatever the values of the corresponding parameter added with '.csv' - e.g. 'Germany' -> 'Germany.csv'. This will make the country list truly dynamic. Thanks.

@pardf Updated the implementation by creating a method get_supported_countries() in param store and removing the countries map which was earlier created.

**Pull request merged**
