### PR TITLE
Advanced ui pre-access control update

### PR DESCRIPTION
**Pull request by pardf**
- Upgrade dash and its associated components
- Added bcrypt, mysql connector, etc in preparation for access control
- Update waiting page ui for consistency with advanced ui
- Added Selenium web test script
- Updated secrets in .env.default for the webapp

### CODE REVIEW

**Review by kariso2000 — APPROVED** [review]

**Comment by pardf** [comment]
Hi @kariso2000 could you check why the unit check fails after update of .env,default?

>> ValueError: Redis URL must specify one of the following schemes (redis://, rediss://, unix://)

Perhaps the secrets of dev needs to be updated?

**Comment by kariso2000** [comment]
Hi @pardf - This is failing due to missing .env file.  I think we should refactor the redis code so that local dev and CI only use flask cache.

**Comment by pardf** [comment]
> 
> 
> Hi @pardf - This is failing due to missing .env file. I think we should refactor the redis code so that local dev and CI only use flask cache.

Thanks @kariso2000 but we need to put in the .env file anyway into the dev? There may be features used in Redis not supported or compatible with Flask cache

Alternatively, we need to continue to use Redis cache with .env

**Comment by kariso2000** [comment]
@pardf Just to confirm this failure is not on dev as the pull request has not taken place.  This is happening in the CI pipeline in github.  I saw on https://flask-caching.readthedocs.io/en/latest/ that it does not mention that FileSystemCache is not thread safe.  Do you think we can use this instead ?

**Comment by kariso2000** [comment]
@pardf Due to other code dependancies we cannot use FileSystemCache.  However for the CI run we can implement - https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-redis-service-containers.

I'll get this set up.

**Pull request merged**
