### PR TITLE
Added graph sampling and abstract methods to connect nodes

### PR DESCRIPTION
**Pull request by thefirebanks**
Added:

- Sampling for graphs (25% of the population), run time now is 1-2 minutes
- Methods to connect nodes by some property (such as ethnicity) and by some activity (such as a food queue or a religious activity)

Refactored `nn_model.py` and deleted unnecessary files with repeated code

### CODE REVIEW

**Comment by tanmaylaud** [comment]
@thefirebanks , this PR contains a lot of abm model changes which are still in dev stage. 

Can we promote these changes ? @ankit1997

**Comment by ankit1997** [comment]
@tanmaylaud , for abm, model validation and functional testing are in-progress. 
@billlyzhaoyh can you suggest if it ok for abm code to be merged into uat? Any pre-requisites we need to do before merging to uat? Can we make changes later on (if any)?

**Comment by pardf** [comment]
> @tanmaylaud , for abm, model validation and functional testing are in-progress.
> @billlyzhaoyh can you suggest if it ok for abm code to be merged into uat? Any pre-requisites we need to do before merging to uat? Can we make changes later on (if any)?
> @serrgaia @vekimenko FYI

Let test it in dev before merging to the uat, also need to resolve the conflict(s) as well

**Comment by kariso2000** [comment]
Your code changes should only be pulled into dev not uat

**Pull request closed without merging**
